### ISSUE TITLE
The strange ICE version.

### ISSUE THREAD

**Issue by logue** [Shadowth117/Zamboni#2]
Since the June 2023 patch, some files output strange headers and cannot be extracted.

Here's the output of the next version of NGSPacker that's in development, but the version numbers were obviously weird:
[NgsPacker.log](https://github.com/Shadowth117/Zamboni/files/11781278/NgsPacker.log)

**Comment by Shadowth117** [comment]
Some of these appear to be .awb files, aka AFS2 magic. 
It is still very possible however that there are problems. Please remove non ICE files from the list. 
At this time, I do not want to add Criware support to Zamboni.
![image](https://github.com/Shadowth117/Zamboni/assets/11241286/20361471-7171-49af-a2db-5e1087a10c44)
